export let allTimezones = [
  {
    id: "1",
    name: "IST",
    fullName: "India Standard Time",
    tz: "Asia/Kolkata",
    country: "India",
  },
  {
    id: "2",
    name: "EST",
    fullName: "Eastern Standard Time",
    tz: "America/New_York",
    country: "USA",
  },
  {
    id: "3",
    name: "CST",
    fullName: "Central Standard Time",
    tz: "America/Chicago",
    country: "USA",
  },
  {
    id: "4",
    name: "PST",
    fullName: "Pacific Standard Time",
    tz: "America/Los_Angeles",
    country: "USA",
  },
  {
    id: "5",
    name: "UTC",
    fullName: "Coordinated Universal Time",
    tz: "UTC",
    country: "Worldwide",
  },
  {
    id: "6",
    name: "GMT",
    fullName: "Greenwich Mean Time",
    tz: "Europe/London",
    country: "UK",
  },
  {
    id: "7",
    name: "AEDT",
    fullName: "Australian Eastern Daylight Time",
    tz: "Australia/Sydney",
    country: "Australia",
  },
  {
    id: "8",
    name: "JST",
    fullName: "Japan Standard Time",
    tz: "Asia/Tokyo",
    country: "Japan",
  },
  {
    id: "9",
    name: "AST",
    fullName: "Arabian Standard Time",
    tz: "Asia/Dubai",
    country: "UAE",
  },
  {
    id: "10",
    name: "BRST",
    fullName: "Brasília Summer Time",
    tz: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    id: "11",
    name: "AKST",
    fullName: "Alaska Standard Time",
    tz: "America/Anchorage",
    country: "USA",
  },
  {
    id: "12",
    name: "HST",
    fullName: "Hawaii Standard Time",
    tz: "Pacific/Honolulu",
    country: "USA",
  },
  {
    id: "13",
    name: "EET",
    fullName: "Eastern European Time",
    tz: "Europe/Athens",
    country: "Europe",
  },
  {
    id: "14",
    name: "MST",
    fullName: "Mountain Standard Time",
    tz: "America/Denver",
    country: "USA",
  },
  {
    id: "15",
    name: "NZST",
    fullName: "New Zealand Standard Time",
    tz: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    id: "16",
    name: "CET",
    fullName: "Central European Time",
    tz: "Europe/Paris",
    country: "Europe",
  },
  {
    id: "17",
    name: "SAST",
    fullName: "South Africa Standard Time",
    tz: "Africa/Johannesburg",
    country: "South Africa",
  },
  {
    id: "18",
    name: "AKDT",
    fullName: "Alaska Daylight Time",
    tz: "America/Anchorage",
    country: "USA",
  },
  {
    id: "19",
    name: "EAT",
    fullName: "East Africa Time",
    tz: "Africa/Nairobi",
    country: "Africa",
  },
  {
    id: "20",
    name: "PDT",
    fullName: "Pacific Daylight Time",
    tz: "America/Los_Angeles",
    country: "USA",
  },
  {
    id: "21",
    name: "NST",
    fullName: "Newfoundland Standard Time",
    tz: "America/St_Johns",
    country: "Canada",
  },
  {
    id: "22",
    name: "CST",
    fullName: "China Standard Time",
    tz: "Asia/Shanghai",
    country: "China",
  },
  {
    id: "23",
    name: "IST",
    fullName: "Israel Standard Time",
    tz: "Asia/Jerusalem",
    country: "Israel",
  },
  {
    id: "24",
    name: "MSK",
    fullName: "Moscow Standard Time",
    tz: "Europe/Moscow",
    country: "Russia",
  },
  {
    id: "25",
    name: "BRT",
    fullName: "Brasília Time",
    tz: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    id: "26",
    name: "CET",
    fullName: "Central European Time",
    tz: "Europe/Paris",
    country: "France",
  },
  {
    id: "27",
    name: "AEDT",
    fullName: "Australian Eastern Daylight Time",
    tz: "Australia/Sydney",
    country: "Australia",
  },
  {
    id: "28",
    name: "PST",
    fullName: "Pakistan Standard Time",
    tz: "Asia/Karachi",
    country: "Pakistan",
  },
  {
    id: "29",
    name: "AST",
    fullName: "Arabian Standard Time",
    tz: "Asia/Dubai",
    country: "UAE",
  },
  {
    id: "30",
    name: "SAST",
    fullName: "South Africa Standard Time",
    tz: "Africa/Johannesburg",
    country: "South Africa",
  },
  {
    id: "31",
    name: "KST",
    fullName: "Korea Standard Time",
    tz: "Asia/Seoul",
    country: "South Korea",
  },
  {
    id: "32",
    name: "NZST",
    fullName: "New Zealand Standard Time",
    tz: "Pacific/Auckland",
    country: "New Zealand",
  },
  {
    id: "33",
    name: "WET",
    fullName: "Western European Time",
    tz: "Europe/Lisbon",
    country: "Portugal",
  },
  {
    id: "34",
    name: "MSD",
    fullName: "Moscow Daylight Time",
    tz: "Europe/Moscow",
    country: "Russia",
  },
  {
    id: "35",
    name: "SAST",
    fullName: "Singapore Standard Time",
    tz: "Asia/Singapore",
    country: "Singapore",
  },
  {
    id: "36",
    name: "IST",
    fullName: "Irish Standard Time",
    tz: "Europe/Dublin",
    country: "Ireland",
  },
  {
    id: "37",
    name: "ART",
    fullName: "Argentina Time",
    tz: "America/Argentina/Buenos_Aires",
    country: "Argentina",
  },
  {
    id: "38",
    name: "CLT",
    fullName: "Chile Standard Time",
    tz: "America/Santiago",
    country: "Chile",
  },
  {
    id: "39",
    name: "SGT",
    fullName: "Singapore Time",
    tz: "Asia/Singapore",
    country: "Singapore",
  },

  {
    id: "41",
    name: "WAT",
    fullName: "West Africa Time",
    tz: "Africa/Lagos",
    country: "Nigeria",
  },
  {
    id: "42",
    name: "EET",
    fullName: "Eastern European Time",
    tz: "Europe/Athens",
    country: "Greece",
  },
  {
    id: "43",
    name: "HKT",
    fullName: "Hong Kong Time",
    tz: "Asia/Hong_Kong",
    country: "Hong Kong",
  },
  {
    id: "44",
    name: "PST",
    fullName: "Philippine Standard Time",
    tz: "Asia/Manila",
    country: "Philippines",
  },
  {
    id: "45",
    name: "AST",
    fullName: "Atlantic Standard Time",
    tz: "America/Halifax",
    country: "Canada",
  },
  {
    id: "36",
    name: "IST",
    fullName: "Irish Standard Time",
    tz: "Europe/Dublin",
    country: "Ireland",
  },
  {
    id: "37",
    name: "ART",
    fullName: "Argentina Time",
    tz: "America/Argentina/Buenos_Aires",
    country: "Argentina",
  },
  {
    id: "38",
    name: "CLT",
    fullName: "Chile Standard Time",
    tz: "America/Santiago",
    country: "Chile",
  },
  {
    id: "39",
    name: "SGT",
    fullName: "Singapore Time",
    tz: "Asia/Singapore",
    country: "Singapore",
  },

  {
    id: "41",
    name: "WAT",
    fullName: "West Africa Time",
    tz: "Africa/Lagos",
    country: "Nigeria",
  },
  {
    id: "42",
    name: "EET",
    fullName: "Eastern European Time",
    tz: "Europe/Athens",
    country: "Greece",
  },
  {
    id: "43",
    name: "HKT",
    fullName: "Hong Kong Time",
    tz: "Asia/Hong_Kong",
    country: "Hong Kong",
  },
  {
    id: "44",
    name: "PST",
    fullName: "Philippine Standard Time",
    tz: "Asia/Manila",
    country: "Philippines",
  },
  {
    id: "45",
    name: "AST",
    fullName: "Atlantic Standard Time",
    tz: "America/Halifax",
    country: "Canada",
  },
  {
    id: "46",
    name: "AFT",
    fullName: "Afghanistan Time",
    tz: "Asia/Kabul",
    country: "Afghanistan",
  },
  {
    id: "47",
    name: "CST",
    fullName: "Central Standard Time",
    tz: "America/Chicago",
    country: "Mexico",
  },
  {
    id: "48",
    name: "IST",
    fullName: "Irish Standard Time",
    tz: "Europe/Dublin",
    country: "Ireland",
  },
  {
    id: "49",
    name: "EAT",
    fullName: "East Africa Time",
    tz: "Africa/Nairobi",
    country: "Kenya",
  },
  {
    id: "50",
    name: "EEST",
    fullName: "Eastern European Summer Time",
    tz: "Europe/Istanbul",
    country: "Turkey",
  },
  {
    id: "51",
    name: "FJT",
    fullName: "Fiji Time",
    tz: "Pacific/Fiji",
    country: "Fiji",
  },
  {
    id: "53",
    name: "JST",
    fullName: "Japan Standard Time",
    tz: "Asia/Tokyo",
    country: "Japan",
  },
  {
    id: "54",
    name: "KST",
    fullName: "Korea Standard Time",
    tz: "Asia/Seoul",
    country: "South Korea",
  },
  {
    id: "55",
    name: "MST",
    fullName: "Mountain Standard Time",
    tz: "America/Denver",
    country: "USA",
  },
  {
    id: "56",
    name: "NST",
    fullName: "Newfoundland Standard Time",
    tz: "America/St_Johns",
    country: "Canada",
  },
  {
    id: "57",
    name: "PST",
    fullName: "Pacific Standard Time",
    tz: "America/Los_Angeles",
    country: "USA",
  },
  {
    id: "58",
    name: "SAST",
    fullName: "South Africa Standard Time",
    tz: "Africa/Johannesburg",
    country: "South Africa",
  },

  {
    id: "60",
    name: "WET",
    fullName: "Western European Time",
    tz: "Europe/Lisbon",
    country: "Portugal",
  },
  {
    id: "61",
    name: "YST",
    fullName: "Yukon Standard Time",
    tz: "America/Whitehorse",
    country: "Canada",
  },
  {
    id: "62",
    name: "AST",
    fullName: "Atlantic Standard Time",
    tz: "America/Halifax",
    country: "Canada",
  },
  {
    id: "63",
    name: "BRT",
    fullName: "Brasília Time",
    tz: "America/Sao_Paulo",
    country: "Brazil",
  },
  {
    id: "64",
    name: "CST",
    fullName: "China Standard Time",
    tz: "Asia/Shanghai",
    country: "China",
  },
  {
    id: "65",
    name: "DST",
    fullName: "Daylight Saving Time",
    tz: "Various",
    country: "Various",
  },
];
